### ISSUE TITLE
Get Heroku instance set up.

### ISSUE THREAD

**Issue by ZacheryPD** [NCSU-CSC510-Group-E/WolfTutor#11]
We need a heroku instance set up.
We also need a slack instance set up.

**Comment by mgmetro4** [comment]
TO DO:

-fix database issue on live Heroku
-create mock data and test (is it working like we intended?)

**Comment by mgmetro4** [comment]
DID:
- Had to change from team Heroku to personal because you can't connect to the interactive elements on slack without the thing that costs money on the team ('hobby') account

- Started created mock data.

- FOUND A BUG : something is timing out, but the app is still working so I'm ignoring it for now.

TO DO:
- create the rest of the mock data. Need to figure out how to input reservation times and reviews
- create a fresh Slack for production

**Comment by mgmetro4** [comment]
Can create tutors and users. Closing and opening a separate issue for slack
